---
title: "CV"
---

#Biografie

Patrick Uytterhoeven studeerde economische wetenschappen (specialisatie econometrie), wijsbegeerte en actuariële wetenschappen aan de KU Leuven.

Hij heeft een  brede ervaring in tal van uiteenliggende domeinen.

Patrick is zijn carrière gestart in onderzoeksfuncties. In de KBC was hij verantwoordelijk voor conjunctuur - prognoses en analyses van de EU regio. Vervolgens heeft hij aan  universiteiten (RUCA, KUL) mee aan een econometrisch model gebouwd om de impact te meten van prijsschokken van grondstoffen op de Belgische economie. Als assistent van prof Mark Eyskens heeft hij jarenlang de cursus Algemene Economie gedoceerd en is eveneens mede- auteur van een handboek.

Hij heeft een grondige financiële kennis. Als directeur van een risicokapitaalfonds heeft hij honderden financiële doorlichtingen verricht van bedrijven. Tevens was hij lid van directiecomités van bedrijven waarin het risicokapitaalfonds participaties nam. 

Tien jaar lang directeur in een snelgroeiend bedrijf in de milieusector. Ruime ervaring opgebouwd in HR, leiding geven, investeringsprojecten, projectmanagement. 

Als geen ander kan hij de link maken van het operationele naar het financiële. Patrick heeft een sterke achtergrond als Data Scientist en is sterk in het programmeren met R. 

Hij heeft vele jaren financiële vakken gedoceerd in het hoger onderwijs.

Hij is voorzitter geweest van de Werkgroep Industrie Beerse (WIB) die de belangen behartigt van de bedrijven in Beerse en omgeving. 

Hij is hoofd van de studiedienst geweest van de Kempense Kamer voor Handel en Nijverheid (nu VOKA). Nadien is hij actief gebleven in de Kempense Kamer, ondermeer als beheerder en ondervoorzitter. 

Als Plato begeleider heeft hij de coaching op zich genomen van talrijke KMO’s. 

Sinds 2001 heeft hij tal van projecten gerealiseerd voor lokale overheden. Dat betreft diverse doorlichtingen van gemeentelijke diensten en OCMW, interimmanegement, begeleiden van managementteams, financiële haalbaarheidsanalyses. Verder heeft hij als lid van het directiecomité of managementteam tal van bedrijven begeleid.

Beroepservaring


2001 – heden
plaats	diverse projecten  op zelfstandige basis
Functie	Senior Consultant

2006 -  2019
plaats	CVO Antwerpen / AP – Hogeschool
Functie	Lector

1991 – 2001
Plaats	    Watco NV
Functie	    Directeur

1989 – 1991
Plaats	    Spike NV / Strategisch Plan Kempen
Functie	    Directeur risicokapitaalfonds
 

1988 – 1989
Plaats	    Kamer van Koophandel
Functie	    Hoofd studiedienst

1983 – 1988
Plaats	    KU Leuven / Universiteit Antwerpen
Functie	    Onderzoeker

1981 – 1983
Plaats	    KBC (Kredietbank) hoofdzetel 
Functie	    Onderzoeker bij cel macro – economie


# OPLEIDING


## ACADEMISCH 

 KU Leuven 
Datum	    1976 – 1980
Opleiding	    Licentiaat Economische Wetenschappen

KU Leuven 
Datum
Opleiding	    1977 - 1980
    Baccalaureus in de wijsbegeerte

KU Leuven 
Datum
Opleiding	      1980 - 1981
      Gegradueerde in de Actuariële Wetenschappen


## ANDERE OPLEIDINGEN

Koninklijk Vlaams Muziekconservatorium
Datum 	    1976 - 1980
Opleiding	    Eerste prijs klarinet en kamermuziek

# PROJECTEN


### ALGEMEEN

•	Interim-management

•	Financiële haalbaarheidsstudies

•	Doorlichtingen en herstructureringen van bedrijven en lokale overheden

•	Projecten bij intercommunales

•	Strategische plannen

•	Simulatiemodellen

•	Brainstorming en coaching

•	Leidinggevende functies




### CONCREET

•	In 1999 gestart als directeur exploitatie bij Leysen Containerdienst NV. Als snelgroeiend bedrijf een aantal fusies begeleid binnen de groep WATCO. Gedurende twee jaar directeur van SOVABO nv in Zwijndrecht, met als doel de cultuur van SOVABO na de fusie met Leysen Containerdienst, op elkaar af te stemmen.

 
•	Lid van het directiecomité van diverse KMO’s, met uitbouw van opvolgingsystemen op commercieel en financieel gebied.

•	Diverse opleidingen  (Inzicht in de jaarrekening, Budgettering,….) voor de Kempense Kamer voor Handel en Nijverheid en de Kamer van Handel en Nijverheid Mechelen.

•	Lid van de WIT, Werkgroep Industrie Turnhout. De WIT behartigt de belangen van de industrie in Turnhout. Onder meer een model ontwikkeld om het effect te berekenen van uitbreiding van industrieterreinen op de tewerkstelling.

•	Voorzitter van de WIB, Werkgroep Industrie Beerse. Maandelijkse bijeenkomsten met CEO’s van verschillende bedrijven in Beerse, om de belangen  van de industrie in Beerse te behartigen.

•	Actief als begeleider in het Plato project, coaching van kleine KMO’s met groeipotentieel.

•	Begeleiding van de overname en management buy – out van Biddeloo NV door Essers, Gimv en Spike



•	In opdracht van VVSG  grondige doorlichting  van de Vlaamse containerparken in het kader van de aanvaardingsplicht van afvalstoffen. Ontwikkeling van een bijhorend simulatiemodel.

•	Samen met VVSG (Interafval) opstellen van een ondernemingsplan  voor de Afvalmaatschappij Limburg AML (nu Limburg.net). Aansluitend coachen van brainstormdagen en het verrichten van een aantal sensitiviteitsanalyses.

•	Samen met VVSG analyse van de investeringscapaciteit van Limburg.net

•	Grondige doorlichting van de intercommunale IVAREM (operationeel en financieel) met opstelling van een plan om de financiële situatie van de intercommunale te verbeteren.

•	Samen met Aeolus bvba uit Diest heeft Patrick  een vergelijkend onderzoek van de kostenstructuur van het afvalbeheer in de gemeenten van het werkingsgebied van de intercommunale Intercompost.

•	Afvalbeleidsplan voor de gemeente Londerzeel

•	Begeleiding managementteam OCMW Machelen

•	Voor het IOK  als expert aangesteld voor onderhandelingen met FOST+ inzake de inzameling van de fracties PMD en papier en karton

•	Interimmanager van de afdeling grondgebiedzaken in de gemeente Sint-Katelijne-Waver (gedurende een jaar)

•	Doorlichting technische diensten gemeente Bekkevoort en interimmanagement

•	Interim HR manager bij de financiële dienst van de VDAB (half jaar)

•	Begeleiding van de opstart van managementteams in diverse steden en gemeenten:

    + OCMW Kortrijk
    + OCMW Londerzeel
    + OCMW Sint-Katelijne-Waver
    + Gemeente Oostkamp
    + OCMW Machelen
    + Gemeente Brecht

•	Handboek “Managementteams in openbare besturen”, uitgegeven bij Politeia



•	Organisatiedoorlichtingen van lokale besturen

    + Stad Herk - de Stad (gemeente + OCMW)
    + Gemeente Oud - Turnhout (gemeente + OCMW)
    + Gemeente Ravels (technische diensten)
    + Gemeente Hove (technische diensten)

•	 Doorlichting en herstructurering van de dienst Mobiliteit en Verkeer van de stad Hasselt

•	Opleiding “Omgaan met moeilijke mensen aan de balie”, diverse gemeentebesturen en OCMW’s

•	Doorlichting PMD - sortering intercommunale IMOG

•	 Doorlichting personeelsbezetting en efficiëntie verbrandingsoven intercommunale IMOG

•	Doorlichting en herstructurering van de dienst Mobiliteit en Verkeer van de stad Hasselt

•	Gemeente Rumst (2009): opstellen van een instrument om kosten en opbrengsten maandelijks te beoordelen, rekening houdend met onderliggende trends en seizoenfactoren. Op die manier kon maandelijks beoordeeld worden of kosten / opbrengsten ondanks schommelingen binnen de verwachtingen bleven. 

•	audit van het rusthuis “Parkhof”, gemeente Machelen (2009).

•	voordracht congres van de gemeentelijke ontvangers, België (2009). Onder de titel “Het verhaal van de gemeente K, een story over een financiële   tsunami in het land van steden en  gemeenten”, een boeiend verhaal over het sturen van gemeentelijke cash flow

•	Opleiding financieel management voor openbare besturen voor WIVO (2009 en 2016)

•	Studieopdracht: Strategisch Plan lokale economie voor de stad Turnhout (2005 – 2006)

•	Ontwikkelen en uittesten van een toetsingskader lokale economie (gezamenlijke opdracht van provincie Antwerpen en Unizo (2007)

•	“Waar ondernemers welkom zijn”, handleiding lokale economie, geschreven in opdracht van de provincie Antwerpen (2007)


